linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
  staticcheck:
    go: "1.20"
  stylecheck:
    go: "1.20"
  unused:
    go: "1.20"

run:
  timeout: 10m
  skip-files:
  - "zz_generated.*\\.go$"
  allow-parallel-runners: true

