name: build container image

on: push

jobs:
  build:
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # because of using public registry

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      #
      # For commit
      #
      - name: Docker meta
        if: ! startsWith( github.ref, 'refs/tags/v' )
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: public.ecr.aws/f5j9d0q5/seaman
          tags: |
            type=sha,prefix=,format=long
            type=ref,event=branch
      - name: Build
        if: ! startsWith( github.ref, 'refs/tags/v' )
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=none
            APP_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #
      # For tag
      #
      - name: Docker meta for push tag
        if: startsWith( github.ref, 'refs/tags/v' )
        id: meta-withtag
        uses: docker/metadata-action@v4
        with:
          images: public.ecr.aws/f5j9d0q5/seaman
          tags: type=semver,pattern={{version}}
      - name: Build for push tag
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta-withtag.outputs.tags }}
          labels: ${{ steps.meta-withtag.outputs.labels }}
          build-args: |
            APP_VERSION=${{ steps.meta-withtag.outputs.tags }}
            APP_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

