name: build container image when tags are pushed

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/seaman
          tags: |
            type=sha,prefix=,format=long
            type=ref,event=branch

      - id: get-tag
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
            echo "::set-output name=tag::$(echo ${{ github.ref }} | sed -e 's|^refs/tags/\(.*\)$|\1|g')"
          else
            echo "::set-output name=tag::none"
          fi

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ steps.get-tag.outputs.tag }}
            APP_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
